server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    driver-class-name:
    username: root
    password: aA@12345678
    url: jdbc:mysql://localhost:3306/identity_service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true