server:
  port: 8080
  servlet:
    context-path: /identity
jwt:
  signerKey: UlCFXMjIMtTYduhI2UP7xrnln3dRSHzXutc50cHjiwM+oTsVad/Ow5Po51yDcbBS
  valid-duration: 3600 #in second
  refreshable-duration: 86400 # in second
spring:
  application:
    name: identity-service
  datasource:
    driver-class-name:
    username: root
    password: aA@12345678
    url: jdbc:mysql://localhost:3306/identity_service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true